[package]
name = "dm_dxe_core"
version = "0.3.2"
edition = "2024"
license = "BSD-2-Clause-Patent"

[dependencies]
  log = { version = "^0.4", default-features = false, features = [ "release_max_level_warn", ] }
  patina_adv_logger = { version = "2", registry = "patina-fw" }
  patina_debugger = { version = "2", registry = "patina-fw" }
  patina_dxe_core = { version = "2", registry = "patina-fw" }
  patina_mm = { version = "2", registry = "patina-fw" }
  patina_samples = { version = "2", registry = "patina-fw" }
  patina_sdk = { version = "2", registry = "patina-fw" }
  patina_section_extractor = { version = "2", registry = "patina-fw" }
  patina_stacktrace = { version = "2", registry = "patina-fw" }
  r-efi = { version = "^5", default-features = false }

# These release settings reduce the binary size significantly
[profile.release]
  codegen-units = 1
  debug = "full"
  lto = true
  opt-level = "s"
  split-debuginfo = "packed"
  strip = "symbols"
  incremental = true

[profile.dev]
  opt-level = 3

[profile.test]
  opt-level = 0
