[package]
name = "dm_dxe_core"
version = "0.1.0"
edition = "2024"
license = "BSD-2-Clause-Patent"

[dependencies]
  log = { version = "^0.4", default-features = false, features = [ "release_max_level_trace", ] }
  patina_adv_logger = { version = "4", registry = "patina-fw" }
  patina_debugger = { version = "4", registry = "patina-fw" }
  patina_dxe_core = { path = "../patina/patina_dxe_core" }
  patina_sdk = { version = "4", registry = "patina-fw" }
  patina_section_extractor = { version = "4", registry = "patina-fw" }

# These release settings reduce the binary size significantly
[profile.release]
  codegen-units = 1
  debug = "full"
  lto = true
  opt-level = "s"
  split-debuginfo = "packed"
  strip = "symbols"
  incremental = true

[profile.dev]
  opt-level = 3

[profile.test]
  opt-level = 0
