# @file publish-binaries.yml
#
# A workflow for publishing QEMU DXE Core binaries.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Publish Binaries

    runs-on: windows-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: ‚úÖ Checkout Repository ‚úÖ
        uses: actions/checkout@v6

      - name: üõ†Ô∏è Download Rust Tools üõ†Ô∏è
        uses: OpenDevicePartnership/patina-devops/.github/actions/rust-tool-cache@main

      - name: Setup artifacts directories
        run: |
          mkdir -p artifacts/debug
          mkdir -p artifacts/release
          mkdir -p artifacts/debug/debugger

      - name: Build Q35 Debug
        run: |
          cargo make q35
          cp target/x86_64-unknown-uefi/debug/qemu_q35_dxe_core.efi artifacts/debug/qemu_q35_dxe_core.efi
          cp target/x86_64-unknown-uefi/debug/qemu_q35_dxe_core.pdb artifacts/debug/qemu_q35_dxe_core.pdb

      - name: Build SBSA Debug
        run: |
          cargo make sbsa
          cp target/aarch64-unknown-uefi/debug/qemu_sbsa_dxe_core.efi artifacts/debug/qemu_sbsa_dxe_core.efi
          cp target/aarch64-unknown-uefi/debug/qemu_sbsa_dxe_core.pdb artifacts/debug/qemu_sbsa_dxe_core.pdb

      - name: Build Q35 Release
        run: |
          cargo make q35-release
          cp target/x86_64-unknown-uefi/release/qemu_q35_dxe_core.efi artifacts/release/qemu_q35_dxe_core.efi
          cp target/x86_64-unknown-uefi/release/qemu_q35_dxe_core.pdb artifacts/release/qemu_q35_dxe_core.pdb

      - name: Build SBSA Release
        run: |
          cargo make sbsa-release
          cp target/aarch64-unknown-uefi/release/qemu_sbsa_dxe_core.efi artifacts/release/qemu_sbsa_dxe_core.efi
          cp target/aarch64-unknown-uefi/release/qemu_sbsa_dxe_core.pdb artifacts/release/qemu_sbsa_dxe_core.pdb

      - name: Build Q35 Debug (Debugger)
        run: |
          cargo make q35 --features enable_debugger
          cp target/x86_64-unknown-uefi/debug/qemu_q35_dxe_core.efi artifacts/debug/debugger/qemu_q35_dxe_core.efi
          cp target/x86_64-unknown-uefi/debug/qemu_q35_dxe_core.pdb artifacts/debug/debugger/qemu_q35_dxe_core.pdb

      - name: Build SBSA Debug (Debugger)
        run: |
          cargo make sbsa --features enable_debugger
          cp target/aarch64-unknown-uefi/debug/qemu_sbsa_dxe_core.efi artifacts/debug/debugger/qemu_sbsa_dxe_core.efi
          cp target/aarch64-unknown-uefi/debug/qemu_sbsa_dxe_core.pdb artifacts/debug/debugger/qemu_sbsa_dxe_core.pdb

      - name: Upload Binaries
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v6
        with:
          name: qemu-dxe-core
          path: artifacts/

      - name: Publish Release Asset
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-Archive -Path artifacts/* -DestinationPath patina_dxe_core_qemu.zip
          gh release upload ${{ github.event.release.tag_name }} patina_dxe_core_qemu.zip
